image: python:3.12

include:
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

.vars:
  variables:
    MANIFEST_PATH: io.gitlab.gregorni.Letterpress.json
    FLATPAK_MODULE: letterpress
    APP_ID: io.gitlab.gregorni.Letterpress
    RUNTIME_REPO: https://nightly.gnome.org/gnome-nightly.flatpakrepo
    BUNDLE: letterpress.flatpak

# Build Flatpak for x86_64
flatpak@x86_64:
  stage: build
  extends:
    - .flatpak@x86_64
    - .vars

# Build Flatpak for aarch64
flatpak@aarch64:
  stage: build
  extends:
    - .flatpak@aarch64
    - .vars

pre-commit:
  script:
    - pip install pre-commit --quiet
    - pre-commit run --all-files
