image: python:3.12

include:
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

.vars:
  variables:
    MANIFEST_PATH: io.gitlab.gregorni.Letterpress.Devel.json
    FLATPAK_MODULE: letterpress
    APP_ID: io.gitlab.gregorni.Letterpress.Devel
    RUNTIME_REPO: https://nightly.gnome.org/gnome-nightly.flatpakrepo
    BUNDLE: letterpress.flatpak

# Build Flatpak for x86_64
flatpak@x86_64:
  extends:
    - .flatpak@x86_64
    - .vars

# Build Flatpak for aarch64
flatpak@aarch64:
  extends:
    - .flatpak@aarch64
    - .vars

nightly@x86_64:
  extends: .publish_nightly
  needs:
    - flatpak@x86_64

nightly@aarch64:
  extends: .publish_nightly
  needs:
    - flatpak@aarch64
